[package]
name = "oxide-geo-ops"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
oxide-core.workspace = true
oxide-geo.workspace = true
oxide-math.workspace = true
faer.workspace = true
rayon.workspace = true
robust.workspace = true
tracing.workspace = true
thiserror.workspace = true
serde.workspace = true
glam.workspace = true

[lints]
workspace = true
