[package]
name = "oxide-plugins-wasm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
oxide-core.workspace = true
wasmtime.workspace = true
wasmtime-wasi.workspace = true
wit-bindgen.workspace = true
serde.workspace = true
tracing.workspace = true
thiserror.workspace = true

[lints]
workspace = true
