[package]
name = "oxide-sim-cfd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
oxide-core.workspace = true
oxide-sim-core.workspace = true
oxide-math.workspace = true
rayon.workspace = true
ndarray.workspace = true
tracing.workspace = true
thiserror.workspace = true
serde.workspace = true

[lints]
workspace = true
