[package]
name = "oxide-cam"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
oxide-core.workspace = true
oxide-geo.workspace = true
oxide-math.workspace = true
oxide-scene.workspace = true
rstar.workspace = true
petgraph.workspace = true
rayon.workspace = true
serde.workspace = true

[lints]
workspace = true
