[package]
name = "oxide-collab"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
oxide-core.workspace = true
oxide-persist.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
automerge.workspace = true
axum.workspace = true
tracing.workspace = true
thiserror.workspace = true
serde.workspace = true

[lints]
workspace = true
