[package]
name = "oxide-test-utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
oxide-core.workspace = true
oxide-geo.workspace = true
oxide-math.workspace = true
proptest.workspace = true
insta.workspace = true
rstest.workspace = true

[lints]
workspace = true
