[package]
name = "oxide-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
oxide-core.workspace = true
oxide-scene.workspace = true
oxide-math.workspace = true
wgpu.workspace = true
naga.workspace = true
encase.workspace = true
bytemuck.workspace = true
glam.workspace = true
half.workspace = true
image.workspace = true
palette.workspace = true
tracing.workspace = true
serde.workspace = true
thiserror.workspace = true

[lints]
workspace = true
