[package]
name = "oxide-geo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
oxide-core.workspace = true
oxide-math.workspace = true
nalgebra.workspace = true
glam.workspace = true
slotmap.workspace = true
smallvec.workspace = true
indexmap.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true
